/*
 * GUS (gokrazy update service)
 *
 * OpenAPI for GUS (gokrazy update service)
 *
 * API version: 1.5.0
 * Contact: michael+gokrazy@stapelberg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gusapi

// TODO
type HeartbeatRequestHumanReadable struct {
	// Linux kernel version
	Kernel string `json:"kernel,omitempty"`
	// Model
	Model string `json:"model,omitempty"`
}
