/*
 * GUS (gokrazy update service)
 *
 * OpenAPI for GUS (gokrazy update service)
 *
 * API version: 1.5.0
 * Contact: michael+gokrazy@stapelberg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gusapi

type HeartbeatRequest struct {
	MachineId string `json:"machine_id,omitempty"`
	// TODO
	Hostname string `json:"hostname,omitempty"`
	SbomHash string `json:"sbom_hash,omitempty"`
	Sbom *HeartbeatRequestSbom `json:"sbom,omitempty"`
	HumanReadable *HeartbeatRequestHumanReadable `json:"human_readable,omitempty"`
}
