/*
 * GUS (gokrazy update service)
 *
 * OpenAPI for GUS (gokrazy update service)
 *
 * API version: 1.4.0
 * Contact: michael+gokrazy@stapelberg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gusapi

type PathHash struct {
	// relative or absolute file path
	Path string `json:"path,omitempty"`
	// TODO
	Hash string `json:"hash,omitempty"`
}
