/*
 * GUS (gokrazy update service)
 *
 * OpenAPI for GUS (gokrazy update service)
 *
 * API version: 1.5.0
 * Contact: michael+gokrazy@stapelberg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gusapi

type IngestRequest struct {
	// The regexp pattern (go regexp syntax) to match the machineIDs to which apply the provided version. The most base case is a plain machine_id.
	MachineIdPattern string `json:"machine_id_pattern,omitempty"`
	SbomHash string `json:"sbom_hash,omitempty"`
	// the type of registry on which the build is stored. see download_link
	RegistryType string `json:"registry_type,omitempty"`
	// relative (localdisk registry) or absolute download link with which gokrazy devices can download the build
	DownloadLink string `json:"download_link,omitempty"`
	// the policy with which the version (sbom_hash) is set for the matching machine_id_pattern. At the moment these are the two possible values: - \"\" (empty string): this is the default value for this property. And it means the provided version (sbom_hash) is temporarily set for the matching machine_id_pattern.   when a new image is ingested for this matching pattern, the new image will become the new desired version for this matching pattern. - \"permanent\": the provided version (sbom_hash) will stay the desired one for the matching machine_id_pattern until it gets explicitly unset/changed.
	IngestionPolicy string `json:"ingestion_policy,omitempty"`
}
